version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    ports: "5432:5432"
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: alicebee/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/media/
    depends_on:
      - db

  frontend:
    env_file: .env
    image: alicebee/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/

  gateway:
    image: alicebee/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static/
      - media:/media/
    depends_on:
      - frontend
